name: Android CI

on:
  push:
    branches: [ "hookhandle" ]
  workflow_dispatch:

permissions:
  contents: write  # Release oluşturmak için write izni gerekli

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: |
        echo 'org.gradle.caching=true' >> gradle.properties
        echo 'org.gradle.parallel=true' >> gradle.properties
        echo 'org.gradle.vfs.watch=true' >> gradle.properties
        echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
        ./gradlew publishToMavenLocal
        ./gradlew --stop
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.maven_pgp_signingKey }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_pgp_signingPassword }}

    - name: Upload library
      uses: actions/upload-artifact@v4
      with:
        name: library
        path: ~/.m2/repository/
        include-hidden-files: true
        if-no-files-found: error

    - name: Get latest tag
      id: get_tag
      run: |
        git fetch --tags
        TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "Latest tag: $TAG"
        if [ -z "$TAG" ]; then
          TAG="0.0"  # Eğer hiç tag yoksa başlangıç değeri olarak 0.0 kullan
        fi
        VERSION=$(echo $TAG | awk -F. '{print $1"."$2+1}')
        echo "New version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Create new tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git tag -a ${{ env.version }} -m "Release ${{ env.version }}"
        git push origin ${{ env.version }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.version }}
        release_name: Release ${{ env.version }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
